### ISSUE TITLE
Update Wohnflächen-Indikatoren

### ISSUE THREAD

**Issue by ksz91** [StataBS/indikatoren#1066]

**Comment by ksz91** [comment]
- 6365 
- 6366

**Comment by ksz91** [comment]
@jb3-2 Please set the same spacing between all bars.

**Comment by jb3-2** [comment]
I have found the problem: Since we use 3 series to display the data, Highcharts wants to put the column of the 1st series to the left, the 2nd in the center, the 3rd to the right. this can be switched off using https://api.highcharts.com/highcharts/series.column.grouping 

![image](https://user-images.githubusercontent.com/7261044/45944026-e891fe80-bfe8-11e8-8c65-1b273abdb023.png)

**Comment by JE1982** [comment]
all updated charts are live now
