### ISSUE TITLE
How to add nbsp without printing it to to the legend?

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#535]
Example: branch 498; id: 6387

![image](https://user-images.githubusercontent.com/23261816/33839052-84c18d3c-de91-11e7-972d-318c43045256.png)

It works for id 6243

**Comment by jb3-2** [comment]
I have found and fixed the problem for all mappies: 

![image](https://user-images.githubusercontent.com/7261044/33883717-243c1a48-df3d-11e7-84ef-be29ada2e14a.png)

We now have the possibility to hide legend bubbles/pies on zoom and have the bubbles/pies grow together with the map on zoom, see chart 6009 (http://issue-498--retailer-seawater-16683.netlify.com/chart.html?id=6009). To do this, we have to set a css class to legend elements that should be hidden when zoom is > 100%, see: 

![image](https://user-images.githubusercontent.com/7261044/33883750-4cf30e92-df3d-11e7-9217-c58e3e325d05.png)

The problem is: I have not communicated this to you, and have not updated mappie001_print.js. This is now done. 

It's up to you if you want to continue creating mappie charts with pies/bubbles that do not grow upon zoom, or if they should grow but hide the legendCircles (as implemented in 6009). Let me know if you have any further questions.

**Comment by larafaelivrin** [comment]
Problem nbsp: If I understand correctly cssClass is set to _undefined_, and useHtml it set to _true_
 
Bubble zoom: In my opnion it is nicer to creat mappie charts with pies/bubbles that grow together with the map zoom and to hide id when the zoom is > 100%. Thus, I will implement this for all bubble charts.

**Comment by jb3-2** [comment]
Exactly. Check 6009 on how to implement. Let me know if you need more info!
