### ISSUE TITLE
svg Problems

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#706]
http://issue-683--retailer-seawater-16683.netlify.com/?Indikatorenset=Arbeitsmarkt

Large space between legend and plot 
![image](https://user-images.githubusercontent.com/23261816/36789329-6e2683f0-1c91-11e8-91f8-41c02db8cec3.png)

Legend Text no present: 
![image](https://user-images.githubusercontent.com/23261816/36789348-7fb3a080-1c91-11e8-99b0-c1822ba0bb87.png)

**Comment by jb3-2** [comment]
It looks like you have Highcharts 6 installed to be used with the export server. We currently use 5.0.17. I will show you how to use that version: 

export set HIGHCHARTS_VERSION=5.0.14
npn run reinstall && npm run rebuild

Change this so that each new terminal has the correct version set: 
c9 open ../.bashrc
...scroll down, change Highcharts version to 5.0.14, save.

**Comment by larafaelivrin** [comment]
If we are using 5.0.17 should I not use: export set HIGHCHARTS_VERSION=5.0.**17**? I am slightly confused. Maybe we can update this together.

**Comment by jb3-2** [comment]
Sorry that was a typo: we use 5.0.14.

**Comment by larafaelivrin** [comment]
ok, but Highcharts version to 5.0.14 is already set in c9 open ../.bashrc. I did not have to change anything. Is that normal?

**Comment by larafaelivrin** [comment]
In order to check the highchart version type the following in the terminal: export
Then check if the following variable exists: HIGHCHARTS_VERSION="5.0.14"

**Comment by jb3-2** [comment]
In 3.1.02: the itemWidth was too small, so the svg lost the text for lack of space. This is now fixed in branch issue-683.

**Comment by jb3-2** [comment]
3.3-01 was fixed by doing "npm run rebuild" with highcharts 5.0.14 installed.
