### ISSUE TITLE
Links in Methodology don't work?

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#734]
Why do the links in the methodology go to github? We have the same problem in the pots we want to release next Monday. @jb3-2

**Comment by jb3-2** [comment]
Can you please send me the netlify link that shows the problem? or branch name and chart id?

**Comment by larafaelivrin** [comment]
Sorry, I forgot to attach the link. Eg: https://statabs.github.io/indikatoren/chart-details.html?id=6156

**Comment by jb3-2** [comment]
Thanks for spotting this problem! I am now searching for the root cause. The proximate cause is that the links href urls are enclosed in two types of quotes: 

![screen shot 2018-03-10 at 09 18 38](https://user-images.githubusercontent.com/7261044/37239963-39d31554-2444-11e8-8610-729727776a5e.png)

**Comment by jb3-2** [comment]
OK I have found the problem: When pasting text from Word, quotes are often replaced by "nice" quotes, in this case ' -> ’. These 'nice' quotes are not interpreted as quotes by browsers, thus the links do not work. 

I have added a step in the build process that replaces 'nice' single quotes with correct single quotes. The problem was only present in 6156 (and its sibling for print, 6308). 

Thanks again @larafaelivrin for spotting this bug!
